### PR TITLE
Saturating the output of the QMF to avoid over/under-flows in the decoder

### PR DESCRIPTION
**Pull request by cloppingemu**
In house testing demonstrated possibility of over/under-flows in the output when decoding a full scale sine wave. Saturating the output of the QMF to avoid over/under-flows in the decoder.

### CODE REVIEW

**Comment by sobomax** [comment]
@cloppingemu thank you for your pull request. Do you have any test data to demonstrate the issue in question? That would be really awesome to have, so that I can start building up CI/CD pipeline for this project. Thanks!

**Comment by cloppingemu** [comment]
Hey I didn't look too closely at test.c to follow the implemented pattern and instead, I have to significantly modified test.c (as shown below) to demonstrate the issue.


```
#define BUFFER_SIZE 128

int main(void) {
    // ((2**15) * numpy.sin(numpy.arange(128) * 2*numpy.pi / 16000 * 1000)).clip(-2**15, 2**15 - 1).astype(numpy.int16)
    int16_t input[BUFFER_SIZE] = {
        0,  12539,  23170,  30273,  32767,  30273,  23170,  12539,
        0, -12539, -23170, -30273, -32768, -30273, -23170, -12539,
        0,  12539,  23170,  30273,  32767,  30273,  23170,  12539,
        0, -12539, -23170, -30273, -32768, -30273, -23170, -12539,
        0,  12539,  23170,  30273,  32767,  30273,  23170,  12539,
        0, -12539, -23170, -30273, -32768, -30273, -23170, -12539,
        0,  12539,  23170,  30273,  32767,  30273,  23170,  12539,
        0, -12539, -23170, -30273, -32768, -30273, -23170, -12539,
        0,  12539,  23170,  30273,  32767,  30273,  23170,  12539,
        0, -12539, -23170, -30273, -32768, -30273, -23170, -12539,
        0,  12539,  23170,  30273,  32767,  30273,  23170,  12539,
        0, -12539, -23170, -30273, -32768, -30273, -23170, -12539,
        0,  12539,  23170,  30273,  32767,  30273,  23170,  12539,
        0, -12539, -23170, -30273, -32768, -30273, -23170, -12539,
        0,  12539,  23170,  30273,  32767,  30273,  23170,  12539,
        0, -12539, -23170, -30273, -32768, -30273, -23170, -12539
    };
    uint8_t encoded[BUFFER_SIZE/2];
    int16_t output[BUFFER_SIZE];

    G722_DEC_CTX *g722_dctx;
    G722_ENC_CTX *g722_ectx;


    // ENCODER

    g722_ectx = g722_encoder_new(64000, 0);
    g722_encode(g722_ectx, input, BUFFER_SIZE, encoded);


    // DECODER

    g722_dctx = g722_decoder_new(64000, 0);
    g722_decode(g722_dctx, encoded, BUFFER_SIZE/2, output);


    // For plotting
    for  (int i = 0; i < BUFFER_SIZE; i++)
        fprintf(stdout, "%d, ", output[i]);
    fprintf(stdout, "\n");

    exit(0);
}
```

`uint16_t input[128]` contains the offending input vector. Its a full scale sine wave which, when encoded and subsequently decoded, leads to over and under flows. Proposed changes fix this behavior.

This is likely happening due to the selection of the QMF coefficients in the implementation but since the coefficients are not a part of the G722 standard, this fix ensures that the program works with ANY set of coefficients.

Figure_1

I can have a closer look at test.c to generate an input test file for this case in the coming days.


EDIT:

output[128] without fix = {0, -1, -1, 0, 0, -2, -1, 3, 0, -13, 1, 36, -10, -94, -3, 180, 37, -327, -117, 495, 278, -584, -184, 1339, 2203, 3213, 6115, 10171, 13057, 10907, 455, -13768, -21793, -22614, -23857, -26316, -23390, -13190, 620, 13435, 21019, 23835, 26478, 28587, 24504, 13123, -977, -13471, -21905, -26182, -28210, -27940, -23041, -12884, 547, 13788, 23113, 27839, 30321, 30251, 24450, 12872, -747, -13373, -23533, -30035, -32039, -29559, -22992, -12803, 138, 13625, 24425, 30896, -32132, 31614, 24379, 12729, -166, -12286, -23083, -30854, 32425, -29631, -22299, -12410, -437, 12119, 22915, 30186, -32387, 31080, 23780, 12554, -212, -12366, -22442, -29274, -31934, -29900, -23256, -12783, 30, 12857, 23162, 29583, 32085, 30323, 23608, 12721, -63, -12619, -23364, -30709, 32271, -30640, -23457, -12743, 141, 13054, 23582, 30144, 32288, 29840, 22855, 12304, -64, -12380}

output[128] with fix = {0, -1, -1, 0, 0, -2, -1, 3, 0, -13, 1, 36, -10, -94, -3, 180, 37, -327, -117, 495, 278, -584, -184, 1339, 2203, 3213, 6115, 10171, 13057, 10907, 455, -13768, -21793, -22614, -23857, -26316, -23390, -13190, 620, 13435, 21019, 23835, 26478, 28587, 24504, 13123, -977, -13471, -21905, -26182, -28210, -27940, -23041, -12884, 547, 13788, 23113, 27839, 30321, 30251, 24450, 12872, -747, -13373, -23533, -30035, -32039, -29559, -22992, -12803, 138, 13625, 24425, 30896, 32767, 31614, 24379, 12729, -166, -12286, -23083, -30854, -32768, -29631, -22299, -12410, -437, 12119, 22915, 30186, 32767, 31080, 23780, 12554, -212, -12366, -22442, -29274, -31934, -29900, -23256, -12783, 30, 12857, 23162, 29583, 32085, 30323, 23608, 12721, -63, -12619, -23364, -30709, -32768, -30640, -23457, -12743, 141, 13054, 23582, 30144, 32288, 29840, 22855, 12304, -64, -12380}

**Comment by cloppingemu** [comment]
Test case has been added. I'll leave adding of CI/CD pipeline for this project up to you.

**Comment by sobomax** [comment]
@cloppingemu thanks a bunch! I will try to take a look in the next few days :) 👍

**Comment by sobomax** [comment]
@cloppingemu Pull request is merged and I've created GH Actions pipeline to run on every commit. Thanks again for contribution!!! 

https://github.com/sippy/libg722/actions/workflows/build_and_test.yml

**Pull request merged**
